### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.Vector.size()' on a null object reference

### ISSUE THREAD

**Issue by RyanC159** [RyuuKenshi/Waste-Classifier#1]
Hello, I tried adding your code into mine and it goes to your DetectScreen from a mainMenu screen, if I tried to go back from the DetectScreen to my mainMenu screen, this error shows and the app crashes.
Any advice?

**Comment by DrunkOnBytes** [comment]
Hi @RyanC159, I apologize for the late reply.
I made this app in the initial days of Flutter and it is bound to not work with the current version of Flutter. Also, there were other bugs present that I never fixed. I don't suggest using the code from this app on any current Flutter projects.

**Comment by RyanC159** [comment]
Thank you for replying and no worries.
Do you still do Flutter for your job?
Thank you for the advice and good to know! :D
I did use your code in my final year project and sort of updated it so that
it works with current Flutter version :D
The only weird part was the camera library only works on API 32 I think,
that's just the library's problem.

**Comment by DrunkOnBytes** [comment]
Thank you for understanding @RyanC159.
I work as a Software Engineer and unfortunately, my current tech stack doesn't include Flutter.
Just like you I learned Flutter in college, more so on a whim, and loved its simplicity. So I created multiple projects and 2 packages in Flutter. The packages I still maintain whenever I get some time.

**Comment by RyanC159** [comment]
That's cool! 👍
